In [1]:
import pandas as pd
import numpy as np
data=pd.DataFrame({
    'OriginalFeature':[1,2,3,4,5,6,7],
    'CategoricalFeature':['A','B','A','B','A','B','A']
})
data

   OriginalFeature CategoricalFeature
0                1                  A
1                2                  B
2                3                  A
3                4                  B
4                5                  A
5                6                  B
6                7                  A

In [6]:
# one hot encoding
data1=pd.get_dummies(data,columns=["CategoricalFeature"])
data1

   OriginalFeature  CategoricalFeature_A  CategoricalFeature_B
0                1                  True                 False
1                2                 False                  True
2                3                  True                 False
3                4                 False                  True
4                5                  True                 False
5                6                 False                  True
6                7                  True                 False

In [7]:
# one hot encoding
data2=pd.get_dummies(data,columns=["CategoricalFeature"],drop_first=True)
data2

   OriginalFeature  CategoricalFeature_B
0                1                 False
1                2                  True
2                3                 False
3                4                  True
4                5                 False
5                6                  True
6                7                 False

In [8]:
# EDA - Exploratory Data Analysis
import pandas as pd
df=pd.read_csv("car data.csv")
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [12]:
df.drop("Car_Name",axis=1,inplace=True)

In [13]:
df.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [14]:
pd.get_dummies(df)

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,2014,3.35,5.59,27000,0,False,False,True,True,False,False,True
1,2013,4.75,9.54,43000,0,False,True,False,True,False,False,True
2,2017,7.25,9.85,6900,0,False,False,True,True,False,False,True
3,2011,2.85,4.15,5200,0,False,False,True,True,False,False,True
4,2014,4.60,6.87,42450,0,False,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,False,True,False,True,False,False,True
297,2015,4.00,5.90,60000,0,False,False,True,True,False,False,True
298,2009,3.35,11.00,87934,0,False,False,True,True,False,False,True
299,2017,11.50,12.50,9000,0,False,True,False,True,False,False,True
300,2016,5.30,5.90,5464,0,False,False,True,True,False,False,True

In [17]:
df=pd.get_dummies(df,drop_first=True)
df.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,3.35,5.59,27000,0,False,True,False,True
1,2013,4.75,9.54,43000,0,True,False,False,True
2,2017,7.25,9.85,6900,0,False,True,False,True
3,2011,2.85,4.15,5200,0,False,True,False,True
4,2014,4.60,6.87,42450,0,True,False,False,True

In [22]:
import pandas as pd
room_length=[18,20,10,12,18,11]
room_breadth=[20,20,10,11,19,10]
room_type=["big","big","normal","normal","big","normal"]
data=pd.DataFrame({"length":room_length,"breadth":room_breadth,"Type":room_type})
data

   length  breadth    Type
0      18       20     big
1      20       20     big
2      10       10  normal
3      12       11  normal
4      18       19     big
5      11       10  normal

In [23]:
# adding a feature called area from length and breadth
data['area']=data["length"]*data["breadth"]
data

   length  breadth    Type  area
0      18       20     big   360
1      20       20     big   400
2      10       10  normal   100
3      12       11  normal   132
4      18       19     big   342
5      11       10  normal   110

In [24]:
data[data['area']>300]

   length  breadth Type  area
0      18       20  big   360
1      20       20  big   400
4      18       19  big   342

# Encoding Nominal Variables

## Transforming Numeric (continuous) features to categorical features

In [26]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==1,"Odd","Even")
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']

In [29]:
apartment_area=[4720,2430,4368,3969,6142,7912]
apartment_price=[2360000,1215000,2184000,1984500,3071000,3956000]
data4=pd.DataFrame({"Area":apartment_area,"Price":apartment_price})
data4

   Area    Price
0  4720  2360000
1  2430  1215000
2  4368  2184000
3  3969  1984500
4  6142  3071000
5  7912  3956000

In [30]:
import numpy as np
data4['Price']=np.where(data4['Price']>3000000,'High',np.where(data4['Price']<2000000,'low','medium'))
data4

   Area   Price
0  4720  medium
1  2430     low
2  4368  medium
3  3969     low
4  6142    High
5  7912    High

### Train Validation Split

In [31]:
# refer notes

# 9 marks code

In [1]:
import pandas as pd
df=pd.read_csv("ipl-matches.csv")
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

df.isna().sum()

In [4]:
df[(df['SuperOver']=='Y')& (df['WinningTeam']=="Gujarat Titans")].shape[0]

0

In [5]:
# how many matches won by rcb vs kkr
df[((df["WinningTeam"]=="Royal Challengers Bangalore")&((df['Team1']=='Kolkata Knight Riders')|(df['Team2']=="Kolkata Knight Riders")))].shape[0]

14

In [6]:
# 3. how many mathces won by toss winner of the match
df[df['TossWinner']==df['WinningTeam']].shape[0]

489

In [13]:
# How many match result decided by D/L method & won by wickets
df[(df['method']=="D/L") & (df["WonBy"]=='Wickets')].shape

(8, 20)